### ISSUE TITLE
Widget does not show images if there are brackets in the Folder name in Rise Storage

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-image-folder#16] opened 2015-06-23 18:33 UTC
Steps to reproduce:
1. Create a Folder in Storage that includes brackets in the Folder name (eg "Image Folder Test (with Bracket)").
2. Upload some image files to the Folder created in step 1.
3. Create a Presentation using the Image Folder Widget and select the Folder created in step 1.
4. Preview, or Schedule the presentation to play on your display.

Result:
No images appear in the Scheduled or Previewed Presentation.

How it should work:
Images should appear in the Presentation regardless of whether there are brackets in the Folder name or not.

Link to Presentation:
http://preview.risevision.com/Viewer.html?type=presentation&id=35accb86-55f9-489e-bc9f-bc8041d0a844

OS:
Windows 7

Chrome Version:
43.0.2357.124

**Comment by alanclayton** [comment] 2015-06-23 18:45
@AlexKolenoff can you confirm if this occurs with Video Folder as well?

**Comment by AlexKolenoff** [comment] 2015-06-23 18:48
@alanclayton No, it doesn't happen with Video Folder widget.

**Comment by donnapep** [comment] 2015-07-16 13:32
@alanclayton The issue is in the the third-party slider plugin that we're using. I made an attempt to fix it but it looks like it's going to be more involved. Would it be better to just log a ticket with them?

**Comment by alanclayton** [comment] 2015-07-16 13:37
@donnapep Makes sense to me. Thanks

**Comment by donnapep** [comment] 2015-07-16 13:46
Logged ticket #480825 with ThemePunch - https://themepunch.ticksy.com/ticket/480825

**Comment by donnapep** [comment] 2016-01-07 14:53
Duplicate of https://github.com/Rise-Vision/widget-image-folder/issues/23.

**Closed by donnapep** 2016-01-07 14:53 UTC
Labels: bug
